1. Fix 2 build error with following error message. src/controllers/user.ts:96:5 - error TS2345: Argument of type '{ email: any; password: any; }' is not assignable to parameter of type 'Partial<Document>'.   Object literal may only specify known properties, and 'email' does not exist in type 'Partial<Document>'.
96     email: req.body.email,
       ~~~~~~~~~~~~~~~~~~~~~

src/controllers/user.ts:106:16 - error TS7006: Parameter 'err' implicitly has an 'any' type.

106     user.save((err) => {
                   ~~~

npm ERR! code ELIFECYCLE

2. Use interface when ever possible, refactor the model of user, make it more understandable.
Use the name User to represent the TypeScript type User.
Use the name UserDocument to represent the mongoose documents which can be saved and retrieved from our database